name: Daily Crawl and Version Bump

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC

jobs:
  crawl:
    name: Run Crawl and Check Changes
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ secrets.USER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run crawl script
        run: USER_NAME=${{ secrets.USER_NAME }} yarn crawl:dev

      - name: Check for metadata changes
        run: |
          git diff --quiet src/metadata || echo "CHANGES_FOUND=true" >> $GITHUB_ENV

      - name: Get current version from package.json
        if: env.CHANGES_FOUND == 'true'
        id: version
        run: echo "CURRENT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Increment patch version
        if: env.CHANGES_FOUND == 'true'
        run: |
          NEW_VERSION=$(node -p "v = process.env.CURRENT_VERSION.split('.'); v[2] = parseInt(v[2]) + 1; v.join('.')")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          jq --arg v "$NEW_VERSION" '.version = $v' package.json > tmp.json && mv tmp.json package.json

      - name: Commit and push changes
        if: env.CHANGES_FOUND == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add package.json src/metadata
          git commit -m "chore: auto-update metadata and bump version to $NEW_VERSION"
          git push origin main

      - name: Notify about new version
        if: env.CHANGES_FOUND == 'true'
        run: echo "🚀 New version $NEW_VERSION is ready for publishing!"
